#!/usr/bin/env python3
"""SoD conflict-pair register — the segregation-of-duties population of the
internal-controls matrix, distilled to a machine-usable rule set for ERP GRC
configuration (SAP GRC Access Control / Oracle GRC / native SoD matrices).

Source of truth: `01-model-company/internal-controls-matrix.md` (808 controls,
Check-34-guarded). The register extracts the preventive-segregation population:

  * Tier 1 — the matrix's own adjudicated SoD category (section C2), every row;
  * Tier 2 — SoD-mechanics controls distributed across the other categories:
    dual authorization / dual sign-off / maker-checker / two-person, explicit
    self-approval blocks, independent review/validation/investigation, and
    out-of-band verification.

Precision guards (each earned from a reviewed false positive): the bare word
"separat*" is ONLY honored in "Separate X from Y" objective form or the C2
section — HR "separation" (CTL-132/221/300) and waste "segregation" (CTL-171)
are not duty segregation; generic C26–C33 template text is excluded by the
same rule. The C26–C33 operating-control family (720 detective controls) is
monitoring-class by design and is stated as out of scope, not missing.

Function pairs are extracted only where the objective states them outright
("Separate X from Y" → (X, Y)); every entry carries its verbatim objective and
control activity so nothing is unreadable without the source.

Modes:
  (default)      regenerate 01-model-company/sod-conflict-register.{md,json}
  --check ROOT   regenerate in memory, byte-compare both artifacts; print
                 SOD_TOTALS + BAD| lines; exit 0 iff identical. Invoked by
                 validate-repo.sh Check 71 every run.
"""

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MATRIX = REPO / "01-model-company" / "internal-controls-matrix.md"
OUT_MD = REPO / "01-model-company" / "sod-conflict-register.md"
OUT_JSON = REPO / "01-model-company" / "sod-conflict-register.json"

SCHEMA = "erpplans-sod-register/1.0"

ROW = re.compile(
    r"^\| (CTL-\d+) \| (.+?) \| ([PD]) \| (.+?) \| (.+?) \| (.+?) \| (.+?) \|$")

MECH = re.compile(
    r"\bdual[- ]?(?:author|approv|control|sign)|\bmaker[/ -]?checker\b|"
    r"\btwo[- ]person\b|\bself[- ]approval\b|\bindependen(?:t|tly|ce)\b|"
    r"\bout-of-band\b|\bsegregation of duties\b", re.I)

PAIR = re.compile(r"^Separate (.+?) from (.+?)$", re.I)


def parse_matrix():
    rows, cur = [], None
    for line in MATRIX.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^## (C\d+\. .+?)\s*$", line)
        if m:
            cur = m.group(1)
            continue
        m = ROW.match(line)
        if m and cur:
            rows.append({
                "id": m.group(1), "section": cur, "objective": m.group(2).strip(),
                "type": m.group(3), "activity": m.group(4).strip(),
                "owner": m.group(5).strip(), "workflows": m.group(6).strip(),
                "req_refs": [r.strip() for r in m.group(7).split(",") if r.strip()],
            })
    assert len(rows) == 808, f"matrix rows {len(rows)} != 808"
    return rows


def classify(rows):
    """Return (register entries, coverage stats). Tier 1 = section C2 (the
    matrix's adjudicated SoD category); Tier 2 = mechanics-matched rows
    elsewhere. Pair extraction only from 'Separate X from Y' objectives."""
    entries = []
    for r in rows:
        in_c2 = r["section"].startswith("C2.")
        pm = PAIR.match(r["objective"])
        mech = MECH.search(r["objective"]) or MECH.search(r["activity"])
        if in_c2:
            tier, kind = 1, "duty-separation"
        elif mech:
            tier = 2
            low = (r["objective"] + " " + r["activity"]).lower()
            kind = next(k for pat, k in (
                (r"dual[- ]?(?:author|approv|control|sign)", "dual-authorization"),
                (r"maker[/ -]?checker|two[- ]person", "maker-checker"),
                (r"self[- ]approval", "self-approval-block"),
                (r"independen(?:t|tly|ce)", "independent-review"),
                (r"out-of-band", "out-of-band-verification"),
                (r"segregation of duties", "duty-separation"),
            ) if re.search(pat, low))
        else:
            continue
        pair = None
        if pm:
            pair = [pm.group(1).strip(), pm.group(2).strip().rstrip(".")]
        entries.append({**r, "tier": tier, "rule_kind": kind, "function_pair": pair})
    return entries


def render(entries, n_total):
    L = []
    A = L.append
    pairs = [e for e in entries if e["function_pair"]]
    t1 = [e for e in entries if e["tier"] == 1]
    t2 = [e for e in entries if e["tier"] == 2]
    A("# SoD Conflict-Pair Register")
    A("")
    A("> **GENERATED ARTIFACT** — regenerated by "
      "[`../07-methodology/sod-register.py`](../07-methodology/sod-register.py) "
      "from the [internal-controls matrix](internal-controls-matrix.md) "
      "(808 controls); byte-verified by validate-repo.sh Check 71 (`--check`) "
      "on every run. Do not hand-edit: change the matrix or the extractor, "
      "then regenerate. Machine-readable twin: "
      "[`sod-conflict-register.json`](sod-conflict-register.json).")
    A("")
    A("> **Purpose:** the preventive-segregation population of the controls "
      "framework, distilled for ERP GRC configuration (access-control rule "
      "sets, workflow approval routing, audit scoping). Every entry carries "
      "its verbatim objective and control activity — nothing here is readable "
      "only through the extraction.")
    A("")
    A("---")
    A("")
    A("## 1. Coverage and method")
    A("")
    A("| Metric | Value |")
    A("|---|---|")
    A(f"| Controls in the matrix | {n_total} |")
    A(f"| Register entries | {len(entries)} |")
    A(f"| Tier 1 — adjudicated SoD category (C2) | {len(t1)} |")
    A(f"| Tier 2 — SoD mechanics distributed in other categories | {len(t2)} |")
    A(f"| Explicit function pairs (`Separate X from Y`) | {len(pairs)} |")
    A("")
    A("Detection: section C2 in full (the matrix's own adjudicated SoD "
      "category), plus dual-authorization / maker-checker / two-person / "
      "self-approval / independent-review / out-of-band-verification mechanics "
      "anywhere else. Two deliberate exclusions keep precision high: bare "
      "*\"separation\"* (HR separations — CTL-132/221/300 are not duty "
      "segregation) and the C26–C33 process-area operating family (720 "
      "detective, monitoring-class by design — out of scope, not missing).")
    A("")
    A("## 2. Function-pair index (GRC rule seeds)")
    A("")
    A("Conflicting duty pairs stated outright by the control objectives:")
    A("")
    A("| Rule | Function A | Function B | CTL | Type |")
    A("|---|---|---|---|---|")
    for e in pairs:
        A(f"| {e['id']}-SOD | {e['function_pair'][0]} | {e['function_pair'][1]} | "
          f"{e['id']} | {e['type']} |")
    A("")
    A("## 3. Full register")
    A("")
    for tier, label in ((1, "Tier 1 — C2 adjudicated SoD category"),
                        (2, "Tier 2 — SoD mechanics, distributed")):
        A(f"### {label} ({len([e for e in entries if e['tier'] == tier])})")
        A("")
        A("| CTL | Objective | Type | Rule kind | Owner roles | Workflows | Req refs |")
        A("|---|---|---|---|---|---|---|")
        for e in entries:
            if e["tier"] != tier:
                continue
            A(f"| {e['id']} | {e['objective'].replace('|', '\\|')} | {e['type']} | "
              f"{e['rule_kind']} | {e['owner'].replace('|', '\\|')} | "
              f"{e['workflows'].replace('|', '\\|')} | {', '.join(e['req_refs'])} |")
        A("")
    A("## 4. GRC usage notes")
    A("")
    A("- The function pairs in §2 are access-control rule seeds: for each, "
      "configure mutually exclusive permission sets so one user cannot hold "
      "both functions; the CTL's workflows column scopes where the conflict "
      "can arise.")
    A("- Dual-authorization entries are workflow-routing rules, not "
      "permission conflicts: model them as two-step approvals with distinct "
      "approvers enforced at submit time.")
    A("- Self-approval blocks are same-user constraints on a specific object "
      "(e.g., CTL-43: the account's Sales Rep cannot be its credit approver) "
      "— enforce as initiator-vs-approver inequality checks.")
    A("- Detective controls in the C26–C33 operating family monitor these "
      "segregations after the fact; their absence from this register is by "
      "design, not a gap.")
    A("")
    return "\n".join(L) + "\n"


def dump(obj) -> str:
    return json.dumps(obj, ensure_ascii=False, indent=1, sort_keys=True) + "\n"


def main() -> int:
    global REPO, MATRIX, OUT_MD, OUT_JSON
    check_only = "--check" in sys.argv
    roots = [a for a in sys.argv[1:] if not a.startswith("--")]
    if roots:
        REPO = Path(roots[0]).resolve()
        MATRIX = REPO / "01-model-company" / "internal-controls-matrix.md"
        OUT_MD = REPO / "01-model-company" / "sod-conflict-register.md"
        OUT_JSON = REPO / "01-model-company" / "sod-conflict-register.json"
    if not MATRIX.exists():
        print("SOD_TOTALS errors=1")
        print(f"BAD|{REPO} is not an erpplans checkout")
        return 1

    rows = parse_matrix()
    entries = classify(rows)
    entries.sort(key=lambda e: (e["tier"], e["id"]))
    doc = {
        "schema": SCHEMA,
        "generated_by": "07-methodology/sod-register.py",
        "source": "01-model-company/internal-controls-matrix.md",
        "counts": {"matrix_controls": len(rows), "register_entries": len(entries),
                   "tier1_c2": sum(1 for e in entries if e["tier"] == 1),
                   "tier2_distributed": sum(1 for e in entries if e["tier"] == 2),
                   "function_pairs": sum(1 for e in entries if e["function_pair"])},
        "controls": sorted(entries, key=lambda e: e["id"]),
    }
    report = render(entries, len(rows))

    bad = []
    if check_only:
        for p, want in ((OUT_MD, report), (OUT_JSON, dump(doc))):
            rel = p.relative_to(REPO)
            if not p.exists():
                bad.append(f"missing: {rel}")
            elif p.read_text(encoding="utf-8") != want:
                bad.append(f"stale (differs from regeneration): {rel}")
    else:
        OUT_MD.write_text(report, encoding="utf-8")
        OUT_JSON.write_text(dump(doc), encoding="utf-8")
        if OUT_MD.read_text(encoding="utf-8") != report or \
           OUT_JSON.read_text(encoding="utf-8") != dump(doc):
            bad.append("write verification failed")

    print(f"SOD_TOTALS entries={len(entries)} "
          f"tier1={doc['counts']['tier1_c2']} tier2={doc['counts']['tier2_distributed']} "
          f"pairs={doc['counts']['function_pairs']} errors={len(bad)}")
    for b in bad:
        print("BAD|" + b)
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
